In [2]:
import pandas as pd

In [13]:
movies= pd.read_csv("movies.csv")
ratings=pd.read_csv("ratings.csv")

print(f"The first 5 rows in movies Dataset:\n{movies.head()}")
print(f"\n The first 5 rows in rating Dataset:\n{ratings.head()}")

The first 5 rows in movies Dataset:
   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy

 The first 5 rows in rating Dataset:
   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [14]:
print(movies.duplicated().sum())

0

In [15]:
print(ratings.duplicated().sum())

0

In [16]:
print(movies.isna().sum())

movieId    0
title      0
genres     0
dtype: int64

In [17]:
print(ratings.isna().sum())

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [ ]:
print(f"the shape of movies Dataset: {movies.shape}")
print(f"the shape of rating Dataset: {ratings.shape}")

the shape of movies Dataset: (9742, 3)
the shape of rating Dataset: (100836, 4)

In [23]:
print(movies.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB
None

In [24]:
print(ratings.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB
None

In [25]:
ratings=ratings.drop('timestamp',axis=1)
ratings.head()

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [28]:
ratings['rating'].describe()

count    100836.000000
mean          3.501557
std           1.042529
min           0.500000
25%           3.000000
50%           3.500000
75%           4.000000
max           5.000000
Name: rating, dtype: float64

In [29]:
movie_data = pd.merge(ratings, movies, on='movieId')

In [30]:
movie_data.head()

,userId,movieId,rating,title,genres
0,1,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [31]:
movie_data.to_csv("cleaned_movie_data.csv", index=False)